services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports: ["9000:9000","9443:9443"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks: [backend]

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports: ["80:80","443:443"]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/www:/srv
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on: [nodered,pgadmin]
    networks: [backend]

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: appdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports: ["5432:5432"]
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/backup:/backup
    networks: [backend]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports: ["5050:80"]
    depends_on: [postgres]
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks: [backend]

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
    ports: ["1880:1880"]
    volumes:
      - ./nodered/data:/data
      - ./nodered/projects:/projects
    networks: [backend]

networks:
  backend:
    driver: bridge

volumes:
  pgadmin-data:
